<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-LIQ39GJJ" failures="1" tests="3" name="Test.newone" time="11.297" errors="0" timestamp="2023-11-05T21:47:58 IST" skipped="0">
  <testcase classname="Test.newone" name="testNavigateToTableDataButton" time="0.113"/>
  <system-out/>
  <testcase classname="Test.newone" name="testEnterDataAndRefreshTable" time="0.653"/>
  <system-out/>
  <testcase classname="Test.newone" name="testAssertionOfData" time="10.531">
    <failure message="expected [[{&quot;name&quot;:&quot;Bob&quot;,&quot;age&quot;:20,&quot;gender&quot;:&quot;male&quot;},{&quot;name&quot;:&quot;George&quot;,&quot;age&quot;:42,&quot;gender&quot;:&quot;male&quot;},{&quot;name&quot;:&quot;Sara&quot;,&quot;age&quot;:42,&quot;gender&quot;:&quot;female&quot;},{&quot;name&quot;:&quot;Conor&quot;,&quot;age&quot;:40,&quot;gender&quot;:&quot;male&quot;},{&quot;name&quot;:&quot;Jennifer&quot;,&quot;age&quot;:42,&quot;gender&quot;:&quot;female&quot;}]] but found [Bob,20,male,George,42,male,Sara,42,female,Conor,40,male,Jennifer,42,female,]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [[{"name":"Bob","age":20,"gender":"male"},{"name":"George","age":42,"gender":"male"},{"name":"Sara","age":42,"gender":"female"},{"name":"Conor","age":40,"gender":"male"},{"name":"Jennifer","age":42,"gender":"female"}]] but found [Bob,20,male,George,42,male,Sara,42,female,Conor,40,male,Jennifer,42,female,]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at Test.newone.testAssertionOfData(newone.java:109)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testAssertionOfData -->
  <system-out/>
</testsuite> <!-- Test.newone -->
